version: '3.7'

services:
  web:
    build: .
    ports:
      - "5005:8000"
    depends_on:
      - db
      - cache
    environment:
      - DATABASE_URL=mongodb://db:27017
      - REDIS_URL=redis://cache:6379

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  cache:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
